compute_environment: LOCAL_MACHINE
debug: true

distributed_type: DEEPSPEED

deepspeed_config:
  deepspeed_config_file: /data/liang.geng/DiffSynth-Studio/examples/wanvideo/model_training/full/ds_config_zero3.json
  zero3_init_flag: false

num_machines: 2
num_processes: 8

machine_rank: 1   # 每台机器不同

rdzv_backend: static
same_network: true

main_training_function: main
enable_cpu_affinity: false

tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false